# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwingEssentials' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SwingEssentials
  pod 'youtube-ios-player-helper', '~> 0.1.6'
  pod 'Braintree', '~> 4.10.0'
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'
  # pod 'Braintree/Venmo'
  # pod 'yoga', :path => "../node_modules/react-native/ReactCommon/yoga"
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  # 'BatchedBridge', # Required For React Native 0.45.0+
  # 'Core',
  # Add any other subspecs you want to use in your project
# ]
  # pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'SwingEssentials-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwingEssentialsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

end
